<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RouteSeeder extends Seeder
{
    private const JSON_COLUMNS = ['image_list_url'];

    public function run(): void
    {
        $rows = $this->rows();

        $rows = $this->encodeJsonColumns($rows);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('routes')->insert($chunk);
        }
    }

    private function encodeJsonColumns(array $rows): array
    {
        foreach ($rows as &$row) {
            foreach (self::JSON_COLUMNS as $column) {
                if (array_key_exists($column, $row) && is_array($row[$column])) {
                    $row[$column] = json_encode($row[$column], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
                }
            }
        }
        unset($row);

        return $rows;
    }

    private function rows(): array
    {
        return [
            [
                'id' => 1,
                'province_start_id' => 1,
                'province_end_id' => 2,
                'name' => 'Hà Nội - Sapa',
                'slug' => 'ha-noi-sapa',
                'title' => 'Vé xe Hà Nội - Sapa',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Hà Nội - Sapa',
                'duration' => '6h - 7h 30m',
                'distance_km' => 315,
                'price_default' => 290000,
                'thumbnail_url' => '/assets/client/images/city_imgs/sapa.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/sapa.jpg'],
                'content' => '<p><strong>Hà Nội - Sapa</strong></p><p>Lịch chạy: 07:00:00 - 13:15:00, 13:30:00 - 19:30:00, 22:00:00 - 05:30:00</p><p>Điểm đón: 210 Trần Quang Khải</p><p>Điểm trả: 458 Điện Biên Phủ</p><p>Giá: Giường nằm 250.000 VND, Cabin đơn 380.000 VND, Cabin đôi 570.000 VND</p>',
                'available_hotel_pickup' => 1,
                'priority' => 0,
                'created_at' => '2025-10-02 23:27:41',
                'updated_at' => '2026-04-07 02:42:10',
            ],
            [
                'id' => 2,
                'province_start_id' => 2,
                'province_end_id' => 1,
                'name' => 'Sapa - Hà Nội',
                'slug' => 'sapa-ha-noi',
                'title' => 'Vé xe Sapa - Hà Nội',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Sapa - Hà Nội',
                'duration' => '6h',
                'distance_km' => 315,
                'price_default' => 290000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Sapa - Hà Nội</strong></p><p>Lịch chạy: 11:00:00 - 17:00:00, 14:00:00 - 20:00:00, 16:00:00 - 22:00:00, 22:00:00 - 04:00:00</p><p>Điểm đón: 458 Điện Biên Phủ</p><p>Điểm trả: 210 Trần Quang Khải</p><p>Giá: Giường nằm 250.000 VND, Cabin đơn 380.000 VND, Cabin đôi 570.000 VND</p>',
                'available_hotel_pickup' => 1,
                'priority' => 0,
                'created_at' => '2025-10-02 23:27:41',
                'updated_at' => '2026-04-07 02:42:10',
            ],
            [
                'id' => 47,
                'province_start_id' => 2,
                'province_end_id' => 7,
                'name' => 'Sapa - Ninh Bình',
                'slug' => 'sapa-ninh-binh',
                'title' => 'Vé xe Sapa - Ninh Bình',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Sapa - Ninh Bình',
                'duration' => '9h 30m',
                'distance_km' => 390,
                'price_default' => 560000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p><strong>Sapa - Ninh Bình</strong></p><p>Lịch chạy: 11:00:00 - 20:30:00</p><p>Điểm đón: 458 Điện Biên Phủ</p><p>Điểm trả: No 2a, đường 27/7 - TP Ninh Bình; Travel Agent - Mike\'s travel agency - Tam Cốc</p><p>Giá: Giường nằm 480.000 VND, Cabin đơn 630.000 VND, Cabin đôi 880.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 1,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:10',
            ],
            [
                'id' => 48,
                'province_start_id' => 7,
                'province_end_id' => 2,
                'name' => 'Ninh Bình - Sapa',
                'slug' => 'ninh-binh-sapa',
                'title' => 'Vé xe Ninh Bình - Sapa',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Ninh Bình - Sapa',
                'duration' => '9h 15m',
                'distance_km' => 390,
                'price_default' => 560000,
                'thumbnail_url' => '/assets/client/images/city_imgs/sapa.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/sapa.jpg'],
                'content' => '<p><strong>Ninh Bình - Sapa</strong></p><p>Lịch chạy: 04:00:00 - 13:15:00</p><p>Điểm đón: No 2a, đường 27/7 - TP Ninh Bình; Travel Agent - Mike\'s travel agency - Tam Cốc</p><p>Điểm trả: 458 Điện Biên Phủ</p><p>Giá: Giường nằm 480.000 VND, Cabin đơn 630.000 VND, Cabin đôi 880.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 97,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:10',
            ],
            [
                'id' => 49,
                'province_start_id' => 2,
                'province_end_id' => 8,
                'name' => 'Sapa - Phong Nha',
                'slug' => 'sapa-phong-nha',
                'title' => 'Vé xe Sapa - Phong Nha',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Sapa - Phong Nha',
                'duration' => '16h 30m',
                'distance_km' => 620,
                'price_default' => 880000,
                'thumbnail_url' => '/assets/client/images/city_imgs/phong-nha.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/phong-nha.jpg'],
                'content' => '<p><strong>Sapa - Phong Nha</strong></p><p>Lịch chạy: 11:00:00 - 03:30:00</p><p>Điểm đón: 458 Điện Biên Phủ</p><p>Điểm trả: Central Backpacker Phong Nha</p><p>Giá: Giường nằm 730.000 VND, Cabin đơn 1.070.000 VND, Cabin đôi 1.500.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 5,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:10',
            ],
            [
                'id' => 50,
                'province_start_id' => 8,
                'province_end_id' => 2,
                'name' => 'Phong Nha - Sapa',
                'slug' => 'phong-nha-sapa',
                'title' => 'Vé xe Phong Nha - Sapa',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Phong Nha - Sapa',
                'duration' => '15h 45m',
                'distance_km' => 620,
                'price_default' => 880000,
                'thumbnail_url' => '/assets/client/images/city_imgs/sapa.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/sapa.jpg'],
                'content' => '<p><strong>Phong Nha - Sapa</strong></p><p>Lịch chạy: 21:30:00 - 13:15:00</p><p>Điểm đón: Central Backpacker Phong Nha</p><p>Điểm trả: 458 Điện Biên Phủ</p><p>Giá: Giường nằm 730.000 VND, Cabin đơn 1.070.000 VND, Cabin đôi 1.500.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 95,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 51,
                'province_start_id' => 2,
                'province_end_id' => 9,
                'name' => 'Sapa - Huế',
                'slug' => 'sapa-hue',
                'title' => 'Vé xe Sapa - Huế',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Sapa - Huế',
                'duration' => '20h',
                'distance_km' => 700,
                'price_default' => 880000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hue.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hue.jpg'],
                'content' => '<p><strong>Sapa - Huế</strong></p><p>Lịch chạy: 11:00:00 - 07:00:00</p><p>Điểm đón: 458 Điện Biên Phủ</p><p>Điểm trả: 07 Đội Cung- TP Huế</p><p>Giá: Giường nằm 730.000 VND, Cabin đơn 1.070.000 VND, Cabin đôi 1.500.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 2,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 52,
                'province_start_id' => 9,
                'province_end_id' => 2,
                'name' => 'Huế - Sapa',
                'slug' => 'hue-sapa',
                'title' => 'Vé xe Huế - Sapa',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Huế - Sapa',
                'duration' => '20h 15m',
                'distance_km' => 700,
                'price_default' => 880000,
                'thumbnail_url' => '/assets/client/images/city_imgs/sapa.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/sapa.jpg'],
                'content' => '<p><strong>Huế - Sapa</strong></p><p>Lịch chạy: 17:00:00 - 13:15:00</p><p>Điểm đón: 07 Đội Cung- TP Huế</p><p>Điểm trả: 458 Điện Biên Phủ</p><p>Giá: Giường nằm 730.000 VND, Cabin đơn 1.070.000 VND, Cabin đôi 1.500.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 93,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 53,
                'province_start_id' => 2,
                'province_end_id' => 10,
                'name' => 'Sapa - Đà Nẵng',
                'slug' => 'sapa-da-nang',
                'title' => 'Vé xe Sapa - Đà Nẵng',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Sapa - Đà Nẵng',
                'duration' => '23h',
                'distance_km' => 790,
                'price_default' => 1000000,
                'thumbnail_url' => '/assets/client/images/city_imgs/da-nang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/da-nang.jpg'],
                'content' => '<p><strong>Sapa - Đà Nẵng</strong></p><p>Lịch chạy: 11:00:00 - 10:00:00</p><p>Điểm đón: 458 Điện Biên Phủ</p><p>Điểm trả: Số 28 đường 3/2- TP Đà Nẵng</p><p>Giá: Giường nằm 850.000 VND, Cabin đơn 1.230.000 VND, Cabin đôi 1.880.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 3,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 54,
                'province_start_id' => 10,
                'province_end_id' => 2,
                'name' => 'Đà Nẵng - Sapa',
                'slug' => 'da-nang-sapa',
                'title' => 'Vé xe Đà Nẵng - Sapa',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Đà Nẵng - Sapa',
                'duration' => '23h',
                'distance_km' => 790,
                'price_default' => 1000000,
                'thumbnail_url' => '/assets/client/images/city_imgs/sapa.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/sapa.jpg'],
                'content' => '<p><strong>Đà Nẵng - Sapa</strong></p><p>Lịch chạy: 14:15:00 - 13:15:00</p><p>Điểm đón: Số 28 đường 3/2- TP Đà Nẵng</p><p>Điểm trả: 458 Điện Biên Phủ</p><p>Giá: Giường nằm 850.000 VND, Cabin đơn 1.230.000 VND, Cabin đôi 1.880.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 91,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 55,
                'province_start_id' => 2,
                'province_end_id' => 11,
                'name' => 'Sapa - Hội An',
                'slug' => 'sapa-hoi-an',
                'title' => 'Vé xe Sapa - Hội An',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Sapa - Hội An',
                'duration' => '25h 30m',
                'distance_km' => 820,
                'price_default' => 1000000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hoi-an.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hoi-an.jpg'],
                'content' => '<p><strong>Sapa - Hội An</strong></p><p>Lịch chạy: 11:00:00 - 12:30:00</p><p>Điểm đón: 458 Điện Biên Phủ</p><p>Điểm trả: 105 Tôn Đức Thắng - TP Hội An</p><p>Giá: Giường nằm 850.000 VND, Cabin đơn 1.230.000 VND, Cabin đôi 1.880.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 4,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 56,
                'province_start_id' => 11,
                'province_end_id' => 2,
                'name' => 'Hội An - Sapa',
                'slug' => 'hoi-an-sapa',
                'title' => 'Vé xe Hội An - Sapa',
                'description' => 'Đặt vé xe giường nằm, cabin đơn, cabin đôi chất lượng cao tuyến Hội An - Sapa',
                'duration' => '23h 45m',
                'distance_km' => 820,
                'price_default' => 1000000,
                'thumbnail_url' => '/assets/client/images/city_imgs/sapa.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/sapa.jpg'],
                'content' => '<p><strong>Hội An - Sapa</strong></p><p>Lịch chạy: 13:30:00 - 13:15:00</p><p>Điểm đón: 105 Tôn Đức Thắng - TP Hội An</p><p>Điểm trả: 458 Điện Biên Phủ</p><p>Giá: Giường nằm 850.000 VND, Cabin đơn 1.230.000 VND, Cabin đôi 1.880.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 89,
                'created_at' => '2026-03-19 04:09:22',
                'updated_at' => '2026-04-07 02:42:11',
            ],
            [
                'id' => 57,
                'province_start_id' => 5,
                'province_end_id' => 1,
                'name' => 'Cát Bà - Hà Nội',
                'slug' => 'cat-ba-ha-noi',
                'title' => 'Vé xe Cát Bà - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Cát Bà - Hà Nội',
                'duration' => '3h 30m',
                'distance_km' => 158,
                'price_default' => 320000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Cát Bà - Hà Nội</strong></p><p>Khung giờ: 08:15:00 - 11:45:00, 12:00:00 - 15:30:00, 15:15:00 - 18:45:00, 16:15:00 - 19:45:00</p><p>Điểm đón: 217 Mot Thang Tu</p><p>Điểm trả: 19 Hang Thiec</p><p>Giá vé tham khảo: 370.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 60,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:45:52',
            ],
            [
                'id' => 58,
                'province_start_id' => 10,
                'province_end_id' => 1,
                'name' => 'Đà Nẵng - Hà Nội',
                'slug' => 'da-nang-ha-noi',
                'title' => 'Vé xe Đà Nẵng - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Đà Nẵng - Hà Nội',
                'duration' => '16h 30m',
                'distance_km' => 742,
                'price_default' => 530000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Đà Nẵng - Hà Nội</strong></p><p>Khung giờ: 14:15:00 - 06:45:00</p><p>Điểm đón: 3 Thang 2 street; 3 Thang 2 street; 3 Thang 2 street</p><p>Điểm trả: 208 Tran Quang Khai; 208 Tran Quang Khai; 208 Tran Quang Khai</p><p>Giá vé tham khảo: 500.000 - 1.070.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 59,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 59,
                'province_start_id' => 10,
                'province_end_id' => 11,
                'name' => 'Đà Nẵng - Hội An',
                'slug' => 'da-nang-hoi-an',
                'title' => 'Vé xe Đà Nẵng - Hội An',
                'description' => 'Đặt vé xe chất lượng cao tuyến Đà Nẵng - Hội An',
                'duration' => '1h',
                'distance_km' => 45,
                'price_default' => 150000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hoi-an.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hoi-an.jpg'],
                'content' => '<p><strong>Đà Nẵng - Hội An</strong></p><p>Khung giờ: 10:00:00 - 11:00:00, 10:10:00 - 11:10:00</p><p>Điểm đón: 3 Thang 2 street; 3 Thang 2 street</p><p>Điểm trả: 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Giá vé tham khảo: 200.000 - 250.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 58,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 06:03:31',
            ],
            [
                'id' => 60,
                'province_start_id' => 10,
                'province_end_id' => 9,
                'name' => 'Đà Nẵng - Huế',
                'slug' => 'da-nang-hue',
                'title' => 'Vé xe Đà Nẵng - Huế',
                'description' => 'Đặt vé xe chất lượng cao tuyến Đà Nẵng - Huế',
                'duration' => '4h',
                'distance_km' => 180,
                'price_default' => 250000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hue.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hue.jpg'],
                'content' => '<p><strong>Đà Nẵng - Huế</strong></p><p>Khung giờ: 14:15:00 - 18:15:00</p><p>Điểm đón: 3 Thang 2 street; 3 Thang 2 street</p><p>Điểm trả: 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Giá vé tham khảo: 250.000 - 300.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 57,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 61,
                'province_start_id' => 10,
                'province_end_id' => 7,
                'name' => 'Đà Nẵng - Ninh Bình',
                'slug' => 'da-nang-ninh-binh',
                'title' => 'Vé xe Đà Nẵng - Ninh Bình',
                'description' => 'Đặt vé xe chất lượng cao tuyến Đà Nẵng - Ninh Bình',
                'duration' => '14h',
                'distance_km' => 630,
                'price_default' => 530000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p><strong>Đà Nẵng - Ninh Bình</strong></p><p>Khung giờ: 14:15:00 - 04:15:00</p><p>Điểm đón: 3 Thang 2 street; 3 Thang 2 street; 3 Thang 2 street</p><p>Điểm trả: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Travel Agency Tam Coc</p><p>Giá vé tham khảo: 500.000 - 550.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 56,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 62,
                'province_start_id' => 10,
                'province_end_id' => 8,
                'name' => 'Đà Nẵng - Phong Nha',
                'slug' => 'da-nang-phong-nha',
                'title' => 'Vé xe Đà Nẵng - Phong Nha',
                'description' => 'Đặt vé xe chất lượng cao tuyến Đà Nẵng - Phong Nha',
                'duration' => '7h 30m',
                'distance_km' => 338,
                'price_default' => 380000,
                'thumbnail_url' => '/assets/client/images/city_imgs/phong-nha.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/phong-nha.jpg'],
                'content' => '<p><strong>Đà Nẵng - Phong Nha</strong></p><p>Khung giờ: 14:15:00 - 21:45:00</p><p>Điểm đón: 3 Thang 2 street; 3 Thang 2 street</p><p>Điểm trả: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Giá vé tham khảo: 370.000 - 470.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 55,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 63,
                'province_start_id' => 6,
                'province_end_id' => 1,
                'name' => 'Hà Giang - Hà Nội',
                'slug' => 'ha-giang-ha-noi',
                'title' => 'Vé xe Hà Giang - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Giang - Hà Nội',
                'duration' => '6h',
                'distance_km' => 270,
                'price_default' => 370000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Hà Giang - Hà Nội</strong></p><p>Khung giờ: 06:30:00 - 12:30:00, 08:30:00 - 14:30:00, 11:00:00 - 17:00:00, 17:45:00 - 23:45:00, 20:30:00 - 02:30:00</p><p>Điểm đón: 100 Tran Phu Ha Giang; 100 Tran Phu Ha Giang; 100 Tran Phu Ha Giang</p><p>Điểm trả: 210 Tran Quang Khai; 210 Tran Quang Khai; 210 Tran Quang Khai</p><p>Giá vé tham khảo: 370.000 - 500.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 54,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:30:37',
            ],
            [
                'id' => 64,
                'province_start_id' => 1,
                'province_end_id' => 5,
                'name' => 'Hà Nội - Cát Bà',
                'slug' => 'ha-noi-cat-ba',
                'title' => 'Vé xe Hà Nội - Cát Bà',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Cát Bà',
                'duration' => '3h 30m',
                'distance_km' => 158,
                'price_default' => 320000,
                'thumbnail_url' => '/assets/client/images/city_imgs/cat-ba.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/cat-ba.jpg'],
                'content' => '<p><strong>Hà Nội - Cát Bà</strong></p><p>Khung giờ: 07:15:00 - 10:45:00, 10:15:00 - 13:45:00, 12:15:00 - 15:45:00, 13:45:00 - 17:15:00</p><p>Điểm đón: 19 Hang Thiec</p><p>Điểm trả: 217 Mot Thang Tu</p><p>Giá vé tham khảo: 370.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 5,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:45:52',
            ],
            [
                'id' => 65,
                'province_start_id' => 1,
                'province_end_id' => 10,
                'name' => 'Hà Nội - Đà Nẵng',
                'slug' => 'ha-noi-da-nang',
                'title' => 'Vé xe Hà Nội - Đà Nẵng',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Đà Nẵng',
                'duration' => '16h - 18h',
                'distance_km' => 765,
                'price_default' => 630000,
                'thumbnail_url' => '/assets/client/images/city_imgs/da-nang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/da-nang.jpg'],
                'content' => '<p><strong>Hà Nội - Đà Nẵng</strong></p><p>Khung giờ: 17:00:00 - 10:00:00, 17:00:00 - 11:00:00, 18:00:00 - 10:00:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec; 19 Hang Thiec</p><p>Điểm trả: 3 Thang 2 street; 3 Thang 2 street; 3 Thang 2 street</p><p>Giá vé tham khảo: 550.000 - 1.150.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 2,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 66,
                'province_start_id' => 1,
                'province_end_id' => 6,
                'name' => 'Hà Nội - Hà Giang',
                'slug' => 'ha-noi-ha-giang',
                'title' => 'Vé xe Hà Nội - Hà Giang',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Hà Giang',
                'duration' => '6h',
                'distance_km' => 270,
                'price_default' => 370000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-giang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-giang.jpg'],
                'content' => '<p><strong>Hà Nội - Hà Giang</strong></p><p>Khung giờ: 06:30:00 - 12:30:00, 09:00:00 - 15:00:00, 09:15:00 - 15:15:00, 20:00:00 - 02:00:00, 20:30:00 - 02:30:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec; 19 Hang Thiec</p><p>Điểm trả: Ben xe Ha Giang; Ben xe Ha Giang; Ben xe Ha Giang</p><p>Giá vé tham khảo: 370.000 - 500.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 6,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:30:37',
            ],
            [
                'id' => 67,
                'province_start_id' => 1,
                'province_end_id' => 11,
                'name' => 'Hà Nội - Hội An',
                'slug' => 'ha-noi-hoi-an',
                'title' => 'Vé xe Hà Nội - Hội An',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Hội An',
                'duration' => '17h - 18h',
                'distance_km' => 780,
                'price_default' => 630000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hoi-an.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hoi-an.jpg'],
                'content' => '<p><strong>Hà Nội - Hội An</strong></p><p>Khung giờ: 17:00:00 - 11:00:00, 18:00:00 - 11:00:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec; 208 Tran Quang Khai</p><p>Điểm trả: 105 Ton Duc Thang; 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Giá vé tham khảo: 550.000 - 1.150.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 3,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 68,
                'province_start_id' => 1,
                'province_end_id' => 9,
                'name' => 'Hà Nội - Huế',
                'slug' => 'ha-noi-hue',
                'title' => 'Vé xe Hà Nội - Huế',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Huế',
                'duration' => '12h - 18h',
                'distance_km' => 675,
                'price_default' => 560000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hue.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hue.jpg'],
                'content' => '<p><strong>Hà Nội - Huế</strong></p><p>Khung giờ: 17:00:00 - 06:00:00, 17:00:00 - 11:00:00, 18:00:00 - 06:00:00, 18:00:00 - 11:00:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec; 19 Hang Thiec</p><p>Điểm trả: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Giá vé tham khảo: 480.000 - 850.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 1,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 69,
                'province_start_id' => 1,
                'province_end_id' => 7,
                'name' => 'Hà Nội - Ninh Bình',
                'slug' => 'ha-noi-ninh-binh',
                'title' => 'Vé xe Hà Nội - Ninh Bình',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Ninh Bình',
                'duration' => '2h',
                'distance_km' => 90,
                'price_default' => 200000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p><strong>Hà Nội - Ninh Bình</strong></p><p>Khung giờ: 06:10:00 - 08:10:00, 07:10:00 - 09:10:00, 08:10:00 - 10:10:00, 09:10:00 - 11:10:00, 10:10:00 - 12:10:00, 11:10:00 - 13:10:00, 12:10:00 - 14:10:00, 13:10:00 - 15:10:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec; 19 Hang Thiec</p><p>Điểm trả: Mr Khanh Travel Agency Ninh Binh; Tam Coc Boat Station; Trang An Boat Station</p><p>Giá vé tham khảo: 350.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 4,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 70,
                'province_start_id' => 1,
                'province_end_id' => 8,
                'name' => 'Hà Nội - Phong Nha',
                'slug' => 'ha-noi-phong-nha',
                'title' => 'Vé xe Hà Nội - Phong Nha',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Phong Nha',
                'duration' => '9h - 18h',
                'distance_km' => 608,
                'price_default' => 530000,
                'thumbnail_url' => '/assets/client/images/city_imgs/phong-nha.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/phong-nha.jpg'],
                'content' => '<p><strong>Hà Nội - Phong Nha</strong></p><p>Khung giờ: 17:00:00 - 03:00:00, 17:00:00 - 11:00:00, 18:00:00 - 03:00:00, 18:00:00 - 11:00:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec; 19 Hang Thiec</p><p>Điểm trả: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Giá vé tham khảo: 450.000 - 820.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 7,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 71,
                'province_start_id' => 1,
                'province_end_id' => 3,
                'name' => 'Hà Nội - Tuần Châu',
                'slug' => 'ha-noi-tuan-chau',
                'title' => 'Vé xe Hà Nội - Tuần Châu',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hà Nội - Tuần Châu',
                'duration' => '2h 30m',
                'distance_km' => 112,
                'price_default' => 230000,
                'thumbnail_url' => '/assets/client/images/city_imgs/cat-ba.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/cat-ba.jpg'],
                'content' => '<p><strong>Hà Nội - Tuần Châu</strong></p><p>Khung giờ: 07:00:00 - 09:30:00, 08:00:00 - 10:30:00</p><p>Điểm đón: 19 Hang Thiec; 19 Hang Thiec</p><p>Điểm trả: Tuan Chau Harbor; Tuan Chau Harbor</p><p>Giá vé tham khảo: 280.000 - 330.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 8,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:45:52',
            ],
            [
                'id' => 72,
                'province_start_id' => 11,
                'province_end_id' => 10,
                'name' => 'Hội An - Đà Nẵng',
                'slug' => 'hoi-an-da-nang',
                'title' => 'Vé xe Hội An - Đà Nẵng',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hội An - Đà Nẵng',
                'duration' => '1h',
                'distance_km' => 45,
                'price_default' => 200000,
                'thumbnail_url' => '/assets/client/images/city_imgs/da-nang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/da-nang.jpg'],
                'content' => '<p><strong>Hội An - Đà Nẵng</strong></p><p>Khung giờ: 13:30:00 - 14:30:00</p><p>Điểm đón: 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Điểm trả: 3 Thang 2 street; 3 Thang 2 street</p><p>Giá vé tham khảo: 250.000 - 300.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 45,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 06:03:31',
            ],
            [
                'id' => 73,
                'province_start_id' => 11,
                'province_end_id' => 1,
                'name' => 'Hội An - Hà Nội',
                'slug' => 'hoi-an-ha-noi',
                'title' => 'Vé xe Hội An - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hội An - Hà Nội',
                'duration' => '17h',
                'distance_km' => 765,
                'price_default' => 530000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Hội An - Hà Nội</strong></p><p>Khung giờ: 13:30:00 - 06:30:00</p><p>Điểm đón: 105 Ton Duc Thang; 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Điểm trả: 208 Tran Quang Khai; 208 Tran Quang Khai; 208 Tran Quang Khai</p><p>Giá vé tham khảo: 500.000 - 1.070.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 44,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 74,
                'province_start_id' => 11,
                'province_end_id' => 9,
                'name' => 'Hội An - Huế',
                'slug' => 'hoi-an-hue',
                'title' => 'Vé xe Hội An - Huế',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hội An - Huế',
                'duration' => '5h',
                'distance_km' => 225,
                'price_default' => 250000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hue.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hue.jpg'],
                'content' => '<p><strong>Hội An - Huế</strong></p><p>Khung giờ: 13:30:00 - 18:30:00</p><p>Điểm đón: 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Điểm trả: 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Giá vé tham khảo: 250.000 - 300.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 43,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 75,
                'province_start_id' => 11,
                'province_end_id' => 7,
                'name' => 'Hội An - Ninh Bình',
                'slug' => 'hoi-an-ninh-binh',
                'title' => 'Vé xe Hội An - Ninh Bình',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hội An - Ninh Bình',
                'duration' => '15h',
                'distance_km' => 675,
                'price_default' => 530000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p><strong>Hội An - Ninh Bình</strong></p><p>Khung giờ: 13:30:00 - 04:30:00</p><p>Điểm đón: 105 Ton Duc Thang; 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Điểm trả: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Travel Agency Tam Coc</p><p>Giá vé tham khảo: 500.000 - 550.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 42,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 76,
                'province_start_id' => 11,
                'province_end_id' => 8,
                'name' => 'Hội An - Phong Nha',
                'slug' => 'hoi-an-phong-nha',
                'title' => 'Vé xe Hội An - Phong Nha',
                'description' => 'Đặt vé xe chất lượng cao tuyến Hội An - Phong Nha',
                'duration' => '8h 30m',
                'distance_km' => 382,
                'price_default' => 380000,
                'thumbnail_url' => '/assets/client/images/city_imgs/phong-nha.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/phong-nha.jpg'],
                'content' => '<p><strong>Hội An - Phong Nha</strong></p><p>Khung giờ: 13:30:00 - 22:00:00</p><p>Điểm đón: 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Điểm trả: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Giá vé tham khảo: 370.000 - 470.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 41,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 77,
                'province_start_id' => 9,
                'province_end_id' => 10,
                'name' => 'Huế - Đà Nẵng',
                'slug' => 'hue-da-nang',
                'title' => 'Vé xe Huế - Đà Nẵng',
                'description' => 'Đặt vé xe chất lượng cao tuyến Huế - Đà Nẵng',
                'duration' => '4h',
                'distance_km' => 180,
                'price_default' => 250000,
                'thumbnail_url' => '/assets/client/images/city_imgs/da-nang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/da-nang.jpg'],
                'content' => '<p><strong>Huế - Đà Nẵng</strong></p><p>Khung giờ: 07:45:00 - 11:45:00</p><p>Điểm đón: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Điểm trả: 3 Thang 2 street; 3 Thang 2 street; 3 Thang 2 street</p><p>Giá vé tham khảo: 250.000 - 624.500 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 40,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 78,
                'province_start_id' => 9,
                'province_end_id' => 1,
                'name' => 'Huế - Hà Nội',
                'slug' => 'hue-ha-noi',
                'title' => 'Vé xe Huế - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Huế - Hà Nội',
                'duration' => '12h 30m',
                'distance_km' => 562,
                'price_default' => 460000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Huế - Hà Nội</strong></p><p>Khung giờ: 16:45:00 - 05:15:00</p><p>Điểm đón: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Điểm trả: 208 Tran Quang Khai; 208 Tran Quang Khai; 208 Tran Quang Khai</p><p>Giá vé tham khảo: 430.000 - 770.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 39,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 79,
                'province_start_id' => 9,
                'province_end_id' => 11,
                'name' => 'Huế - Hội An',
                'slug' => 'hue-hoi-an',
                'title' => 'Vé xe Huế - Hội An',
                'description' => 'Đặt vé xe chất lượng cao tuyến Huế - Hội An',
                'duration' => '5h',
                'distance_km' => 225,
                'price_default' => 250000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hoi-an.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hoi-an.jpg'],
                'content' => '<p><strong>Huế - Hội An</strong></p><p>Khung giờ: 07:45:00 - 12:45:00</p><p>Điểm đón: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Điểm trả: 105 Ton Duc Thang; 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Giá vé tham khảo: 250.000 - 624.500 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 38,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 80,
                'province_start_id' => 9,
                'province_end_id' => 7,
                'name' => 'Huế - Ninh Bình',
                'slug' => 'hue-ninh-binh',
                'title' => 'Vé xe Huế - Ninh Bình',
                'description' => 'Đặt vé xe chất lượng cao tuyến Huế - Ninh Bình',
                'duration' => '10h',
                'distance_km' => 450,
                'price_default' => 430000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p><strong>Huế - Ninh Bình</strong></p><p>Khung giờ: 16:45:00 - 02:45:00, 18:30:00 - 04:30:00</p><p>Điểm đón: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Điểm trả: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh</p><p>Giá vé tham khảo: 430.000 - 770.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 37,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:30:37',
            ],
            [
                'id' => 81,
                'province_start_id' => 9,
                'province_end_id' => 8,
                'name' => 'Huế - Phong Nha',
                'slug' => 'hue-phong-nha',
                'title' => 'Vé xe Huế - Phong Nha',
                'description' => 'Đặt vé xe chất lượng cao tuyến Huế - Phong Nha',
                'duration' => '3h 30m',
                'distance_km' => 158,
                'price_default' => 300000,
                'thumbnail_url' => '/assets/client/images/city_imgs/phong-nha.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/phong-nha.jpg'],
                'content' => '<p><strong>Huế - Phong Nha</strong></p><p>Khung giờ: 16:45:00 - 20:15:00</p><p>Điểm đón: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Điểm trả: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Giá vé tham khảo: 300.000 - 550.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 36,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 82,
                'province_start_id' => 7,
                'province_end_id' => 10,
                'name' => 'Ninh Bình - Đà Nẵng',
                'slug' => 'ninh-binh-da-nang',
                'title' => 'Vé xe Ninh Bình - Đà Nẵng',
                'description' => 'Đặt vé xe chất lượng cao tuyến Ninh Bình - Đà Nẵng',
                'duration' => '14h',
                'distance_km' => 630,
                'price_default' => 630000,
                'thumbnail_url' => '/assets/client/images/city_imgs/da-nang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/da-nang.jpg'],
                'content' => '<p><strong>Ninh Bình - Đà Nẵng</strong></p><p>Khung giờ: 20:30:00 - 10:30:00</p><p>Điểm đón: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Travel Agency Tam Coc</p><p>Điểm trả: 3 Thang 2 street; 3 Thang 2 street; 3 Thang 2 street</p><p>Giá vé tham khảo: 550.000 - 850.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 35,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 83,
                'province_start_id' => 7,
                'province_end_id' => 1,
                'name' => 'Ninh Bình - Hà Nội',
                'slug' => 'ninh-binh-ha-noi',
                'title' => 'Vé xe Ninh Bình - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Ninh Bình - Hà Nội',
                'duration' => '2h',
                'distance_km' => 90,
                'price_default' => 280000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Ninh Bình - Hà Nội</strong></p><p>Khung giờ: 06:30:00 - 08:30:00, 06:40:00 - 08:40:00, 07:30:00 - 09:30:00, 07:40:00 - 09:40:00, 08:30:00 - 10:30:00, 08:39:00 - 10:39:00, 09:30:00 - 11:30:00, 09:40:00 - 11:40:00</p><p>Điểm đón: Mr Khanh Travel Agency Ninh Binh; Tam Coc Boat Station; Trang An Boat Station</p><p>Điểm trả: 19 Hang Thiec; 19 Hang Thiec; 19 Hang Thiec</p><p>Giá vé tham khảo: 330.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 34,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:45:52',
            ],
            [
                'id' => 84,
                'province_start_id' => 7,
                'province_end_id' => 11,
                'name' => 'Ninh Bình - Hội An',
                'slug' => 'ninh-binh-hoi-an',
                'title' => 'Vé xe Ninh Bình - Hội An',
                'description' => 'Đặt vé xe chất lượng cao tuyến Ninh Bình - Hội An',
                'duration' => '15h',
                'distance_km' => 675,
                'price_default' => 630000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hoi-an.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hoi-an.jpg'],
                'content' => '<p><strong>Ninh Bình - Hội An</strong></p><p>Khung giờ: 20:30:00 - 11:30:00</p><p>Điểm đón: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Travel Agency Tam Coc</p><p>Điểm trả: 105 Ton Duc Thang; 105 Ton Duc Thang; 105 Ton Duc Thang</p><p>Giá vé tham khảo: 550.000 - 850.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 33,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 85,
                'province_start_id' => 7,
                'province_end_id' => 9,
                'name' => 'Ninh Bình - Huế',
                'slug' => 'ninh-binh-hue',
                'title' => 'Vé xe Ninh Bình - Huế',
                'description' => 'Đặt vé xe chất lượng cao tuyến Ninh Bình - Huế',
                'duration' => '10h',
                'distance_km' => 450,
                'price_default' => 560000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hue.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hue.jpg'],
                'content' => '<p><strong>Ninh Bình - Huế</strong></p><p>Khung giờ: 20:30:00 - 06:30:00</p><p>Điểm đón: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh</p><p>Điểm trả: 7 Doi Cung Hue; 7 Doi Cung Hue; 7 Doi Cung Hue</p><p>Giá vé tham khảo: 480.000 - 850.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 32,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 86,
                'province_start_id' => 7,
                'province_end_id' => 8,
                'name' => 'Ninh Bình - Phong Nha',
                'slug' => 'ninh-binh-phong-nha',
                'title' => 'Vé xe Ninh Bình - Phong Nha',
                'description' => 'Đặt vé xe chất lượng cao tuyến Ninh Bình - Phong Nha',
                'duration' => '7h',
                'distance_km' => 315,
                'price_default' => 530000,
                'thumbnail_url' => '/assets/client/images/city_imgs/phong-nha.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/phong-nha.jpg'],
                'content' => '<p><strong>Ninh Bình - Phong Nha</strong></p><p>Khung giờ: 20:30:00 - 03:30:00</p><p>Điểm đón: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh</p><p>Điểm trả: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Giá vé tham khảo: 450.000 - 820.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 31,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 87,
                'province_start_id' => 8,
                'province_end_id' => 1,
                'name' => 'Phong Nha - Hà Nội',
                'slug' => 'phong-nha-ha-noi',
                'title' => 'Vé xe Phong Nha - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Phong Nha - Hà Nội',
                'duration' => '9h 30m',
                'distance_km' => 428,
                'price_default' => 330000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Phong Nha - Hà Nội</strong></p><p>Khung giờ: 20:00:00 - 05:30:00, 21:30:00 - 07:00:00</p><p>Điểm đón: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Điểm trả: 208 Tran Quang Khai; 208 Tran Quang Khai; 208 Tran Quang Khai</p><p>Giá vé tham khảo: 300.000 - 700.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 30,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 88,
                'province_start_id' => 8,
                'province_end_id' => 7,
                'name' => 'Phong Nha - Ninh Bình',
                'slug' => 'phong-nha-ninh-binh',
                'title' => 'Vé xe Phong Nha - Ninh Bình',
                'description' => 'Đặt vé xe chất lượng cao tuyến Phong Nha - Ninh Bình',
                'duration' => '7h',
                'distance_km' => 315,
                'price_default' => 330000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p><strong>Phong Nha - Ninh Bình</strong></p><p>Khung giờ: 20:00:00 - 03:00:00, 21:30:00 - 04:30:00</p><p>Điểm đón: Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha; Central Backpackers Hostel Phong Nha</p><p>Điểm trả: Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh; Mr Khanh Travel Agency Ninh Binh</p><p>Giá vé tham khảo: 300.000 - 700.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 29,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-04-07 03:00:12',
            ],
            [
                'id' => 89,
                'province_start_id' => 3,
                'province_end_id' => 1,
                'name' => 'Tuần Châu - Hà Nội',
                'slug' => 'tuan-chau-ha-noi',
                'title' => 'Vé xe Tuần Châu - Hà Nội',
                'description' => 'Đặt vé xe chất lượng cao tuyến Tuần Châu - Hà Nội',
                'duration' => '2h 30m',
                'distance_km' => 112,
                'price_default' => 230000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p><strong>Tuần Châu - Hà Nội</strong></p><p>Khung giờ: 11:30:00 - 14:00:00, 11:45:00 - 14:15:00</p><p>Điểm đón: Tuan Chau Harbor; Tuan Chau Harbor</p><p>Điểm trả: 19 Hang Thiec; 19 Hang Thiec</p><p>Giá vé tham khảo: 280.000 - 330.000 VND</p>',
                'available_hotel_pickup' => 0,
                'priority' => 28,
                'created_at' => '2026-03-19 05:30:37',
                'updated_at' => '2026-03-19 05:45:52',
            ],
            [
                'id' => 90,
                'province_start_id' => 8,
                'province_end_id' => 9,
                'name' => 'Phong Nha - Huế',
                'slug' => 'phong-nha-hue',
                'title' => 'Vé xe Phong Nha - Huế',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Phong Nha - Huế.',
                'duration' => '03:30:00',
                'distance_km' => 220,
                'price_default' => 250000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hue.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hue.jpg'],
                'content' => '<p>Tuyến Phong Nha - Huế được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-04-07 03:15:27',
                'updated_at' => '2026-04-07 03:16:14',
            ],
            [
                'id' => 91,
                'province_start_id' => 8,
                'province_end_id' => 10,
                'name' => 'Phong Nha - Đà Nẵng',
                'slug' => 'phong-nha-da-nang',
                'title' => 'Vé xe Phong Nha - Đà Nẵng',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Phong Nha - Đà Nẵng.',
                'duration' => '06:30:00',
                'distance_km' => 320,
                'price_default' => 380000,
                'thumbnail_url' => '/assets/client/images/city_imgs/da-nang.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/da-nang.jpg'],
                'content' => '<p>Tuyến Phong Nha - Đà Nẵng được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-04-07 03:15:28',
                'updated_at' => '2026-04-07 03:16:14',
            ],
            [
                'id' => 92,
                'province_start_id' => 8,
                'province_end_id' => 11,
                'name' => 'Phong Nha - Hội An',
                'slug' => 'phong-nha-hoi-an',
                'title' => 'Vé xe Phong Nha - Hội An',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Phong Nha - Hội An.',
                'duration' => '07:30:00',
                'distance_km' => 350,
                'price_default' => 380000,
                'thumbnail_url' => '/assets/client/images/city_imgs/hoi-an.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/hoi-an.jpg'],
                'content' => '<p>Tuyến Phong Nha - Hội An được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-04-07 03:15:28',
                'updated_at' => '2026-04-07 03:16:14',
            ],
            [
                'id' => 93,
                'province_start_id' => 1,
                'province_end_id' => 4,
                'name' => 'Hà Nội - Mai Châu',
                'slug' => 'ha-noi-mai-chau',
                'title' => 'Vé xe Hà Nội - Mai Châu',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Hà Nội - Mai Châu.',
                'duration' => '04:30:00',
                'distance_km' => 140,
                'price_default' => 300000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p>Tuyến Hà Nội - Mai Châu được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-05-27 00:00:00',
                'updated_at' => '2026-05-27 00:00:00',
            ],
            [
                'id' => 94,
                'province_start_id' => 4,
                'province_end_id' => 1,
                'name' => 'Mai Châu - Hà Nội',
                'slug' => 'mai-chau-ha-noi',
                'title' => 'Vé xe Mai Châu - Hà Nội',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Mai Châu - Hà Nội.',
                'duration' => '04:30:00',
                'distance_km' => 140,
                'price_default' => 300000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p>Tuyến Mai Châu - Hà Nội được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-05-27 00:00:00',
                'updated_at' => '2026-05-27 00:00:00',
            ],
            [
                'id' => 95,
                'province_start_id' => 1,
                'province_end_id' => 12,
                'name' => 'Hà Nội - Pù Luông',
                'slug' => 'ha-noi-pu-luong',
                'title' => 'Vé xe Hà Nội - Pù Luông',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Hà Nội - Pù Luông.',
                'duration' => '05:30:00',
                'distance_km' => 175,
                'price_default' => 350000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ninh-binh.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ninh-binh.jpg'],
                'content' => '<p>Tuyến Hà Nội - Pù Luông được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-05-27 00:00:00',
                'updated_at' => '2026-05-27 00:00:00',
            ],
            [
                'id' => 96,
                'province_start_id' => 12,
                'province_end_id' => 1,
                'name' => 'Pù Luông - Hà Nội',
                'slug' => 'pu-luong-ha-noi',
                'title' => 'Vé xe Pù Luông - Hà Nội',
                'description' => 'Đặt vé xe giường nằm, cabin, limousine chất lượng cao tuyến Pù Luông - Hà Nội.',
                'duration' => '05:30:00',
                'distance_km' => 175,
                'price_default' => 350000,
                'thumbnail_url' => '/assets/client/images/city_imgs/ha-noi.jpg',
                'image_list_url' => ['/assets/client/images/city_imgs/ha-noi.jpg'],
                'content' => '<p>Tuyến Pù Luông - Hà Nội được King Express Bus khai thác với nhiều lựa chọn xe chất lượng cao, phù hợp cho cả khách du lịch và khách đi công tác.</p><p>Hành khách có thể chọn điểm đón trả thuận tiện, đặt vé trước và theo dõi thông tin chuyến đi rõ ràng.</p>',
                'available_hotel_pickup' => 0,
                'priority' => 0,
                'created_at' => '2026-05-27 00:00:00',
                'updated_at' => '2026-05-27 00:00:00',
            ],
        ];
    }
}
